### PR TITLE
Create a New York Times article clone

### PR DESCRIPTION
**Pull request by fegzycole**
#### What does this PR do?
Creates a webpage aesthetically similar to <https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0>
#### How should this be manually tested?
Visit the Github pages link on <https://bafiam.github.io/NYT-clone/>

### CODE REVIEW

**Review by Redvanisation — CHANGES_REQUESTED** [review]
# Changes required  🛑

### Hello team  🌟

**Good work on this project, but we need to fix the issues below before moving on ⬇️** 

1. The New York Times logo in the navbar should be a link.

2. Please fix the Theory of Inflation section, the images are showing on top of the actual text, it has to look like the original page.

3. The footer should have a fixed position on the bottom of the screen.

### _After making the required changes please submit a new code review request_

### Good luck guys! 🍀

**Comment by bafiam** [comment]
**Hello Redvanisation** ,

Thank you for our feedback.

My Partner and i will work on that asap.

**Review by Forison — COMMENTED** [review]
# Pull request under review by Addo

**Review by Forison — APPROVED** [review]
# Bravo Ferguson  & Stephen 💪
Nice work on implementing the changes suggested by my colleague earlier.🙂
#### I am very impressed with your project😇. At some point, I felt I was on the original page.😇
#### once again, 💪GOOD JOB GUYS💪, Keep it up
Go ahead and merge to master
# Project is approved
#### Happy coding 🙂

**Comment by bafiam** [comment]
**Hello Addo,**

Thank you for our feedback, it means alot to us.

Thank you

**Comment by fegzycole** [comment]
Hey @Forison , 

Thanks alot for the prompt review and your nice feedback.

Best Regards

**Pull request merged**
